-- AlterTable
ALTER TABLE `IntegrationSetting` MODIFY `provider` ENUM('SMTP', 'WHATSAPP_CLOUD', 'SMS_GATEWAY', 'PAYMENT_GATEWAY', 'OBJECT_STORAGE', 'GOOGLE', 'RESEND') NOT NULL;

-- AlterTable
ALTER TABLE `WebhookEvent` MODIFY `provider` ENUM('SMTP', 'WHATSAPP_CLOUD', 'SMS_GATEWAY', 'PAYMENT_GATEWAY', 'OBJECT_STORAGE', 'GOOGLE', 'RESEND') NOT NULL;

