// Writes prisma/migrations/20261002000000_init/migration.sql (MySQL) from prisma/schema.prisma.
// It is used once, to create the first migration without needing a running database.
// For later schema changes use Prisma: npx prisma migrate dev --name what_changed
import { createRequire } from 'node:module'
import fs from 'node:fs'
const require = createRequire(import.meta.url)
const w = require('@prisma/prisma-schema-wasm')
const p = 'prisma/schema.prisma'
let s = fs.readFileSync(p, 'utf8')
const fmt = w.format(JSON.stringify([[p, s]]), JSON.stringify({ textDocument: { uri: 'file:///' + p }, options: { tabSize: 2, insertSpaces: true } }))
try { const o = JSON.parse(fmt); s = Array.isArray(o) ? o[0][1] : fmt } catch { s = fmt }
fs.writeFileSync(p, s)
w.validate(JSON.stringify({ prismaSchema: [[p, s]], noColor: true }))
const { enums, models, indexes } = JSON.parse(w.get_dmmf(JSON.stringify({ prismaSchema: [[p, s]], noColor: true }))).datamodel
const enumOf = Object.fromEntries(enums.map((e) => [e.name, e.values.map((v) => `'${v.name}'`).join(', ')]))
const BASE = { String: 'VARCHAR(191)', Int: 'INTEGER', BigInt: 'BIGINT', Float: 'DOUBLE', Boolean: 'BOOLEAN', DateTime: 'DATETIME(3)', Decimal: 'DECIMAL(65,30)', Json: 'JSON', Bytes: 'LONGBLOB' }
const typeOf = (f) => {
  if (f.kind === 'enum') return `ENUM(${enumOf[f.type]})`
  if (f.nativeType) {
    const [n, a] = f.nativeType
    if (n === 'Char') return `CHAR(${a[0]})`
    if (n === 'VarChar') return `VARCHAR(${a[0]})`
    if (n === 'Text') return 'TEXT'
    if (n === 'Date') return 'DATE'
    if (n === 'Decimal') return `DECIMAL(${a.join(',')})`
    throw new Error(`Unhandled native type ${n} on ${f.name}`)
  }
  return BASE[f.type]
}
const lit = (v) => (typeof v === 'string' ? `'${v.replace(/'/g, "''")}'` : String(v))
const dflt = (f) => {
  const d = f.default
  if (d === undefined || d === null) return ''
  if (typeof d === 'object') return d.name === 'now' ? ' DEFAULT CURRENT_TIMESTAMP(3)' : ''
  return ' DEFAULT ' + lit(d)
}
// MySQL identifiers are at most 64 characters.
const nm = (base, suffix) => ((base + suffix).length <= 64 ? base + suffix : base.slice(0, 64 - suffix.length) + suffix)
const q = (c) => '`' + c + '`'
const out = ['-- CX CRM ERP: first migration (MySQL / MariaDB). Generated from prisma/schema.prisma by scripts/gen-sql.mjs', '']
const fks = []
const used = new Set()
const unique = (name) => { let n = name, i = 1; while (used.has(n)) n = name.slice(0, 61) + '_' + i++; used.add(n); return n }
for (const m of models) {
  const lines = m.fields.filter((f) => f.kind !== 'object').map((f) => `  ${q(f.name)} ${typeOf(f)}${f.isRequired ? ' NOT NULL' : ' NULL'}${dflt(f)}`)
  for (const i of indexes.filter((i) => i.model === m.name && i.type !== 'id')) {
    const cols = i.fields.map((f) => f.name)
    lines.push(`  ${i.type === 'unique' ? 'UNIQUE INDEX' : 'INDEX'} ${q(nm(m.name + '_' + cols.join('_'), i.type === 'unique' ? '_key' : '_idx'))}(${cols.map(q).join(', ')})`)
  }
  const pk = m.primaryKey ? m.primaryKey.fields : m.fields.filter((f) => f.isId).map((f) => f.name)
  lines.push(`  PRIMARY KEY (${pk.map(q).join(', ')})`)
  out.push(`-- CreateTable`, `CREATE TABLE ${q(m.name)} (\n${lines.join(',\n')}\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`, '')
  for (const f of m.fields.filter((f) => f.kind === 'object' && f.relationFromFields?.length)) {
    const od = { Cascade: 'CASCADE', SetNull: 'SET NULL', Restrict: 'RESTRICT', NoAction: 'NO ACTION' }[f.relationOnDelete] ?? (f.isRequired ? 'RESTRICT' : 'SET NULL')
    fks.push(`-- AddForeignKey\nALTER TABLE ${q(m.name)} ADD CONSTRAINT ${q(unique(nm(m.name + '_' + f.relationFromFields.join('_'), '_fkey')))} FOREIGN KEY (${f.relationFromFields.map(q).join(', ')}) REFERENCES ${q(f.type)}(${f.relationToFields.map(q).join(', ')}) ON DELETE ${od} ON UPDATE CASCADE;\n`)
  }
}
out.push(...fks)
fs.mkdirSync('prisma/migrations/20261002000000_init', { recursive: true })
fs.writeFileSync('prisma/migrations/20261002000000_init/migration.sql', out.join('\n'))
fs.writeFileSync('prisma/migrations/migration_lock.toml', '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "mysql"\n')
console.log(`models ${models.length}, enums ${enums.length}, indexes ${indexes.length}, foreign keys ${fks.length}`)
